### ISSUE TITLE
Integrating JupyterHub with Voila's progressive rendering

### ISSUE THREAD

**Issue by InfiniteChai** [ideonate/jhsingle-native-proxy#11]
Hey,

I've been using the jhsingle-native-proxy to expose voila to an authenticated JupyterHub and its working great. However one thing that's been noticed is that we no longer get the spinning loader and instead we have a blank page until the notebook has been fully executed. For some of our more complex applications this can be 15-20 seconds of load time with no visible indicator to users that work is progressing,

After digging into the details, it looks like voila [flushes progressively](https://github.com/voila-dashboards/voila/blob/ae3d025dda21f72c2a663d04cf4ff10dc9215f08/voila/handler.py#L156 ) so that the user is presented with an initial response then progressively sees progress until the notebook execution has completed.

However when sat behind the proxy, [we're waiting](https://github.com/ideonate/jhsingle-native-proxy/blob/24881eb3a5b94cd1432783bc09e092182b1c8e19/jhsingle_native_proxy/proxyhandlers.py#L251) for the response to be completed before writing back out. This means that nothing is rendered to the user until execution has been completed. 

Is this something that has already been witnessed with the proxy and is there a known way to work around it? If not, any suggestion on an approach to look to support it?

**Comment by danlester** [comment]
Thank you for your notes and detailed research!

This isn't something that anyone else has mentioned, or that I've noticed myself, but as you suggest maybe it is more obvious with longer-running scripts.

Similar 'quirks' have come up before though. For example, Streamlit's use of websockets wasn't 100% in line with the protocol (or maybe it was Tornado missing a step...), so jhsingle-native-proxy had to take into account how HTTP cookies were returned unexpectedly during the websocket handshake.

Anyway, yes, it would be good to 'flush' on the jhsingle-native-proxy side (assuming the upstream JupyterHub proxy handles it OK!).

I'd like to take a look at some point, but if it is a blocker for you then please get in touch and we can see if we can work together on this somehow. In any case, it would be great to hear more about how you are using the project. Email dan@ideonate.com if you'd like to discuss.

**Comment by danlester** [comment]
I have made [a commit](https://github.com/ideonate/jhsingle-native-proxy/commit/7264dd23a26c43c7d6c5e827afb81dd45ae31710) that attempts to overcome this problem.

It would be great if you can try it out. Currently only in master branch, not released.

The solution needs to do a bit of processing in Python that it didn't have to do before, so it's possible this will slow things down in the case where the underlying process is not using the 'progressive flushing'. (And also for serving other Voila assets such as CSS and JS.) And there could be other side-effects, so if it is worthwhile for Voila but not other frameworks, maybe this approach needs to become a command-line option.

**Comment by danlester** [comment]
I had a chance to release a beta version in case that is easier for you to install: https://pypi.org/project/jhsingle-native-proxy/0.7.2b1/

**Comment by InfiniteChai** [comment]
That's great, thanks for the quick turnaround on that! We'll get that setup in our test environment and let you know how it goes.

**Comment by InfiniteChai** [comment]
With the inclusion of #12, we tested locally and works great! Thanks for helping with this @danlester.

**Comment by danlester** [comment]
Thanks for trying it out. Great to hear it works, with your fix.

As before, I think it will make sense to make this feature switchable, and include the argument for Voila only really. Anyway, sounds like you're in a position to move forward for now, and might need to look for a switch in the next full release.

**Comment by InfiniteChai** [comment]
Thanks. Are you able to make a beta release with #12 for us to deploy?

Definitely agreed that putting it behind a feature flag makes sense for a main release.

**Comment by danlester** [comment]
No problem, you can now use [jhsingle-native-proxy==0.7.2b2](https://pypi.org/project/jhsingle-native-proxy/0.7.2b2/)

There is a way to install directly from a GitHub commit URL but I think the syntax is different in pip compared to conda, and I can never remember exactly how to do it... And maybe your build system won't allow it anyway.
