### ISSUE TITLE
Websocket max_message_size is too low

### ISSUE THREAD

**Issue by wmalara** [ideonate/jhsingle-native-proxy#14]
Hi, believe it or not, but the [10 MB websocket max_message_size](https://github.com/ideonate/jhsingle-native-proxy/blob/0f9370e6c654366c83997d306f305547ee058835/jhsingle_native_proxy/websocket.py#L69) is too low for my use case :). I would be grateful if you could increase it (let's say to 1 GB) or make it configurable.

**Comment by danlester** [comment]
Thanks for letting me know. I will take a look when I get a chance.

**Comment by danlester** [comment]
This is now available on the command line in jhsingle-native-proxy 0.7.6 and through the following config on cdsdashboards 0.5.5:

```
c.VariableMixin.proxy_websocket_max_message_size = 10*1024*1024
```

https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/useroptions.html

**Comment by wmalara** [comment]
Thank you very much @danlester for this change and for the tool.

**Comment by wmalara** [comment]
Hi @danlester, I'm afraid the last commit reversed the change: https://github.com/ideonate/jhsingle-native-proxy/commit/38878fcae7d47e59d14413b121e864feb8df679b#diff-8a55eeddb853164506d9ee72dba2cd4c297dd7337270e5d549de95dd6fc0b4bf

**Comment by danlester** [comment]
It looks like it, but actually I found out that tornado has its own override as long as `websocket_max_message_size` is a setting in tornado - so most of the code I'd written was irrelevant.

It only really needs this line: https://github.com/ideonate/jhsingle-native-proxy/blob/38878fcae7d47e59d14413b121e864feb8df679b/jhsingle_native_proxy/main.py#L75

Please could you try it out to be sure the functionality really doesn't work?
