### ISSUE TITLE
Error: No such option: --SingleUserNotebookApp.default_url

### ISSUE THREAD

**Issue by Blackmamba23** [ideonate/jhsingle-native-proxy#16]
Getting the following error "Error: No such option: --SingleUserNotebookApp.default_url" when using this package in a single user container image with Jupyterhub. The image is loaded as a profile list of single user environments.

**Comment by Blackmamba23** [comment]
I was able to resolve this issue by excluding the defaultUrl field and any singleUserNotebookApp settings not listed as part of the jhsingle-native-proxy flags.

**Comment by danlester** [comment]
Thanks for letting us know.

**Comment by Blackmamba23** [comment]
Hi @danlester, not a problem mate...just wondering, is this package compatible with jupyterhub's idle culling functionality?

**Comment by danlester** [comment]
Hi there @Blackmamba23 ! I think the docs here should lead you to the relevant functionality: https://cdsdashboards.readthedocs.io/en/stable/chapters/troubleshooting.html#dashboards-and-servers-keep-dying

I guess it depends slightly on what you are hoping to achieve with it!

**Comment by Blackmamba23** [comment]
Hi @danlester, I have setup the idle cull functionality but doesnt seem to be culling the proxied service after the set timeout of inactivity. I have not added the jupyterhub idle culler package to the container image, I wonder if that is something I need to include for to work with this package? Thanks for the link btw!
