### ISSUE TITLE
jhsingle-native-proxy not showing running notebook while using voila until notebook finish its execution

### ISSUE THREAD

**Issue by anfebit** [ideonate/jhsingle-native-proxy#18]
Hi Dan, 

I'm trying to use the jhsingle-native-proxy on top of voila. The authentication works well, until I noticed that when voila is used without the proxy, the behavior is a little different. 

A template is being used that shows the progress of the running notebook while voila is processing it, a template was created that is passed to voilà using the --template flag, this work well along with jupyterhub. However, with jhsingle-native-proxy the notebook is not shown until voilà finishes its execution, therefore, we are not capable to see the progress of the notebook itself. This is very important due to some notebooks taking a while to run, the template shows the progress, while with jhsingle-native-proxy shows a blank page and it only shows the result of converted notebooks when it finishes. For some notebooks, the user will have to wait until the notebooks completes, the user won't know if the notebook is running or not. Is there a a solution to this problem? Any ideas or suggestions? 

Best regards.

**Comment by danlester** [comment]
Hi there! It might be worth adding the `--progressive` flag to the jhsingle-native-proxy command line. This will flush the buffer from underlying service whenever chunks appear. The option was added precisely for that reason when using Voilà.

**Comment by anfebit** [comment]
Thanks Dan, I will add it and I will let you know how it works. OK?

**Comment by anfebit** [comment]
BTW, it works great!

**Comment by anfebit** [comment]
BTW, it works, thanks!
