### ISSUE TITLE
[Feature Request] Binder Button

### ISSUE THREAD

**Issue by prateekrastogi** [ideonate/jhsingle-native-proxy#2]
Having launch with binder button for examples would be greatly appreciated.

Thank you.

**Comment by danlester** [comment]
Thank you very much for the suggestion. The links could be helpful if the Binder examples were 'real', but right now they aren't much use - looking at the code in GitHub is more likely to be informative than running them in Binder.

Please see my [note here](https://discourse.jupyter.org/t/new-package-to-run-arbitrary-web-service-in-jupyterhub-jhsingle-native-proxy/3493/13?u=danlester) why jhsingle-native-proxy doesn't make much sense for Binder at the moment. It is only really useful in an authenticated JupyterHub environment.

If this changes, e.g. ?token auth is added, then having direct mybinder.org links could be useful.

**Comment by prateekrastogi** [comment]
@danlester Thank you. The explanation would suffice my container requirements. :-)

**Comment by prateekrastogi** [comment]
https://github.com/danlester/binderhub-voila-native for those interested ;-)
