### ISSUE TITLE
Jhsingle-native-proxy 0.8.1 logger not outputting log messages to the console

### ISSUE THREAD

**Issue by aditipate** [ideonate/jhsingle-native-proxy#25]
I am using Jhsingle-native-proxy locally and with Docker but despite using the `--debug` option it seems that the `DEBUG` and `INFO` log messages are not being displayed in my console. Currently Jhsingle-native-proxy does not seem to be logging/outputting any log messages seen in proxyhandlers.py to my console. 

I have also noticed that Jhsingle-native-proxy is using the app_log logger from tornado.log, whose level is set to either DEBUG or INFO depending on whether the `--debug` option is used. 

Is there a way to get the log messages to display in the console and fix this issue?

**Comment by aditipate** [comment]
I also have a potential fix for this but can't create a PR. It's saying validation failed: must be a collaborater when I try to open a pull request.

**Comment by danlester** [comment]
@aditipate Do you know if we need to upgrade the minimum Tornado version for this to work though...?
