### ISSUE TITLE
Aiohttp Connector and Timeout Options - Provide Additional Options 

### ISSUE THREAD

**Issue by aditipate** [ideonate/jhsingle-native-proxy#29]
Hello! I'm opening this Issue to request additional click options in jhsingle-native-proxy. Having these additional click options would let you configure the aiohttp.ClientSession(), allowing for greater flexibility in types of applications launched using jhsingle-native-proxy. 
We've found these additional options to be helpful when launching applications using jhsingle-native-proxy. I can't directly open a PR since I'm not a collaborator but here's the branch with the additional updates for the options:  https://github.com/PolusAI/jhsingle-native-proxy 

Additional click options:
Adds additional click options to jhsingle-native-proxy, --aiohttp-no-ssl-connector and --aiohttp-request-timeout, to configure the aiohttp.ClientSession():

--aiohttp-no-ssl-connector - including this option passes a TCP connector to aiohttp.ClientSession() that disables SSL verification. If not included defaults to None.

--aiohttp-request-timeout - allows you to set the maximal number of seconds for the whole request operation including connection establishment, request sending and response reading. Timeout settings for aiohttp are stored in ClientTimeout data structure. Set to 0 to disable and default is 300 as per the aiohttp.ClientTimeout() documentation.

**Comment by danlester** [comment]
Thanks for this - it all looks good if it helps you! I have released v0.8.3.
