### ISSUE TITLE
timeouts

### ISSUE THREAD

**Issue by cneerdaels** [ideonate/jhsingle-native-proxy#3]
I'm using this with jupyterhub and cdsdashboards (the combo is perfect for my use case) but I was having issues with connect timeouts for notebooks that were a bit more computationally expensive. It was hitting the tornado 20 sec default request timeout. My quick and dirty solution was to change the proxy_request_options function to `return dict(follow_redirects=False, request_timeout=300)` I someone mention issues with timeouts and thought posting this might help others. Hardwiring it here fixes my problem, but maybe a more elegant solution is to have jupyterhub's c.Spawner.http_timeout passed along, though I just started playing with all of this last week and don't know the pros and cons of that approach.

Thanks for the awesome work

**Comment by danlester** [comment]
@cneerdaels Thank you very much for filing this report. I will take a look and see if I can find a way to pass this into jhsingle-native-proxy as config perhaps on the command line, and then also via config in [ContainDS Dashboards](https://github.com/ideonate/cdsdashboards) as you suggest.

Please feel free to [get in touch](https://containds.com/support/) to let me know more about how you are getting on with ContainDS Dashboards itself, but in any case I'll reach out if I have any trouble replicating the problem you've described or if I need any advice.

Thanks again!

**Comment by danlester** [comment]
This has now been addressed in the latest release, version 0.1.3.

There is a command-line parameter --request-timeout=300 that you can now set.

More importantly, the default value has been set at 300 anyway, so you should just be able to upgrade to 0.1.3 and use it directly!

This will be configurable in the _next_ version of ContainDS Dashboards. (c.VariableLocalProcessSpawner.proxy_request_timeout = 300 for example)

Thank you very much @cneerdaels  for making this contribution.
